### ISSUE TITLE
Generate a release for different OS

### ISSUE THREAD

**Issue by joakin** [phuedx/copypasta#1]
And link to the releases page in README.

https://github.com/electron-userland/electron-packager

**Comment by phuedx** [comment]
I'll update [the build script](https://github.com/phuedx/copypasta/blob/master/package.json#L21-L22) to package the app for Windows and Linux too.

**Comment by joakin** [comment]
...and this issue lingered forever open 💀

**Comment by phuedx** [comment]
What do you want from me?

**Comment by joakin** [comment]
Nothing 💚 Thanks for the open sourcing!

**Comment by joakin** [comment]
Thanks! You're a 💯 ❌  engineer

**Comment by phuedx** [comment]
See [the v0.1.0 release](phuedx/copypasta/releases/tag/v0.1.0).
